package models;

import models.attackType.Hybrid;
import models.attackType.Melee;
import models.attackType.Ranged;
import models.card.*;
import models.item.*;
import models.magic.Buff;
import models.magic.Spell;
import models.targetsociety.*;
import models.targetsociety.UnitTargetSociety.*;

import java.util.ArrayList;
import java.util.Random;

import static models.SpecialPowerCastTime.*;

public class Initializer {
    private static ArrayList<Item> collectibles = initCollectibleItems();

    public static void initShopCards(ArrayList<Card> shopCards) {
        addMinions(shopCards);
        addHeroes(shopCards);
        addSpells(shopCards);
    }

    private static void addMinions(ArrayList<Card> cards) {
        //minions
        //1
        cards.add(new Minion.MinionBuilder()
                .setAttackType(new Ranged(7))
                .setAp(4)
                .setHp(6)
                .setManaCost(2)
                .setBuyPrice(300)
                .setSellPrice(300)
                .setName("kamandare fars")
                .create()
        );
        //2
        cards.add(new Minion.MinionBuilder()
                .setSpecialPowerCastTime(ON_ATTACK)
                .setSpecialPower(new Spell.SpellBuilder()
                        .addBuff(new Buff.BuffBuilder()
                                .setStun()
                                .setDuration(1)
                                .create())
                        .setTargetSociety(new OneUnit(TargetType.UNIT, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .create())
                .setAttackType(new Melee())
                .setAp(4)
                .setHp(6)
                .setManaCost(2)
                .setSellPrice(400)
                .setBuyPrice(400)
                .setName("shamshir zane fars")
                .create()
        );
        //3
        cards.add(new Minion.MinionBuilder()
                .setAttackType(new Hybrid(3))
                .setAp(3)
                .setHp(5)
                .setManaCost(1)
                .setBuyPrice(500)
                .setSellPrice(500)
                .setName("neize dare fars")
                .create()
        );
        //4
        cards.add(new Minion.MinionBuilder()
                .setAttackType(new Melee())
                .setAp(6)
                .setHp(10)
                .setManaCost(4)
                .setSellPrice(200)
                .setBuyPrice(200)
                .setName("asb savare fars")
                .create()
        );
        //5
        cards.add(new Minion.MinionBuilder()
                .setAddedApPerAttack(5)
                .setAttackType(new Melee())
                .setAp(6)
                .setHp(24)
                .setManaCost(9)
                .setBuyPrice(600)
                .setSellPrice(600)
                .setName("pahlevane fars")
                .create()
        );
        //6
        cards.add(new Minion.MinionBuilder()
                .setCombo()
                .setAttackType(new Melee())
                .setAp(4)
                .setHp(12)
                .setManaCost(7)
                .setSellPrice(800)
                .setBuyPrice(800)
                .setName("sepah salare fars")
                .create()
        );
        //7
        cards.add(new Minion.MinionBuilder()
                .setAttackType(new Ranged(5))
                .setAp(4)
                .setHp(3)
                .setManaCost(1)
                .setBuyPrice(500)
                .setSellPrice(500)
                .setName("kamandare toorani")
                .create()
        );
        //8
        cards.add(new Minion.MinionBuilder()
                .setAttackType(new Ranged(7))
                .setAp(2)
                .setHp(4)
                .setManaCost(1)
                .setSellPrice(600)
                .setBuyPrice(600)
                .setName("ghollab sang dare toorani")
                .create()
        );
        //9
        cards.add(new Minion.MinionBuilder()
                .setAttackType(new Hybrid(3))
                .setAp(4)
                .setHp(4)
                .setManaCost(1)
                .setBuyPrice(600)
                .setSellPrice(600)
                .setName("neize dare toorani")
                .create()
        );
        //10
        cards.add(new Minion.MinionBuilder()
                .setSpecialPowerCastTime(ON_ATTACK)
                .setSpecialPower(new Spell.SpellBuilder()
                        .addBuff(new Buff.BuffBuilder()
                                .setDisarm()
                                .setDuration(1)
                                .create())
                        .addBuff(new Buff.BuffBuilder()
                                .setPoison(1)
                                .setDuration(4)
                                .create())
                        .setTargetSociety(new OneUnit(TargetType.UNIT, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .create())
                .setAttackType(new Melee())
                .setAp(6)
                .setHp(6)
                .setManaCost(4)
                .setBuyPrice(700)
                .setSellPrice(700)
                .setName("jasoose toorani")
                .create()
        );
        //11
        cards.add(new Minion.MinionBuilder()
                .setAttackType(new Melee())
                .setAp(10)
                .setHp(3)
                .setManaCost(2)
                .setSellPrice(450)
                .setBuyPrice(450)
                .setName("gorz dare toorani")
                .create()
        );
        //12
        cards.add(new Minion.MinionBuilder()
                .setCombo()
                .setAttackType(new Melee())
                .setAp(10)
                .setHp(6)
                .setManaCost(6)
                .setSellPrice(800)
                .setBuyPrice(800)
                .setName("shahzadeye toorani")
                .create()
        );
        //13
        cards.add(new Minion.MinionBuilder()
                .setAttackType(new Hybrid(7))
                .setAp(10)
                .setHp(14)
                .setManaCost(9)
                .setBuyPrice(300)
                .setSellPrice(300)
                .setName("dive siah")
                .create()
        );
        //14
        cards.add(new Minion.MinionBuilder()
                .setAttackType(new Ranged(7))
                .setAp(12)
                .setHp(12)
                .setManaCost(9)
                .setBuyPrice(300)
                .setSellPrice(300)
                .setName("ghoole sang andaz")
                .create()
        );
        //15
        cards.add(new Minion.MinionBuilder()
                .setSpecialPowerCastTime(PASSIVE)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.MINION, TargetTeam.FRIEND, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaHP(10)
                                .setHalfTurnDuration()
                                .create())
                        .create())
                .setAttackType(new Ranged(3))
                .setAp(2)
                .setHp(0)
                .setManaCost(2)
                .setSellPrice(200)
                .setBuyPrice(200)
                .setName("oghab")
                .create()
        );
        //16
        cards.add(new Minion.MinionBuilder()
                .setAttackType(new Melee())
                .setAp(8)
                .setHp(16)
                .setManaCost(6)
                .setSellPrice(300)
                .setBuyPrice(300)
                .setName("dive goraz savar")
                .create()
        );
        //17
        cards.add(new Minion.MinionBuilder()
                .setSpecialPowerCastTime(ON_DEATH)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new UnitsAdjacentToCell(TargetType.MINION, TargetTeam.ANY, TargetAttackType.ANY, false))
                        .addBuff(new Buff.BuffBuilder()
                                .setDamage(2)
                                .create())
                        .create())
                .setAttackType(new Hybrid(3))
                .setAp(11)
                .setHp(12)
                .setManaCost(7)
                .setBuyPrice(500)
                .setSellPrice(500)
                .setName("ghoole tak cheshm")
                .create()
        );
        //18
        cards.add(new Minion.MinionBuilder()
                .setSpecialPowerCastTime(ON_ATTACK)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.UNIT, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setPoison(1)
                                .setDuration(3)
                                .create())
                        .create())
                .setAttackType(new Ranged(4))
                .setAp(6)
                .setHp(5)
                .setManaCost(4)
                .setSellPrice(300)
                .setBuyPrice(300)
                .setName("mare sammi")
                .create()
        );
        //19
        cards.add(new Minion.MinionBuilder()
                .setAttackType(new Ranged(4))
                .setAp(5)
                .setHp(9)
                .setManaCost(5)
                .setSellPrice(250)
                .setBuyPrice(250)
                .setName("ezhdehaye atash andaz")
                .create()
        );
        //20
        cards.add(new Minion.MinionBuilder()
                .setPiercingHoly()
                .setAttackType(new Melee())
                .setAp(8)
                .setHp(1)
                .setManaCost(2)
                .setSellPrice(600)
                .setBuyPrice(600)
                .setName("shire darande")
                .create()
        );
        //21
        cards.add(new Minion.MinionBuilder()
                .setSpecialPowerCastTime(ON_SPAWN)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new UnitsInRange(TargetType.MINION, TargetTeam.ANY, TargetAttackType.ANY, 2, false))
                        .addBuff(new Buff.BuffBuilder()
                                .setHoly(-1)
                                .setDuration(Buff.INFINITY)
                                .create())
                        .create())
                .setAttackType(new Ranged(5))
                .setAp(7)
                .setHp(14)
                .setManaCost(8)
                .setBuyPrice(500)
                .setSellPrice(500)
                .setName("mare ghool peykar")
                .create()
        );
        //22
        cards.add(new Minion.MinionBuilder()
                .setSpecialPowerCastTime(ON_ATTACK)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.MINION, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDurationToStart(1)
                                .setDeltaHP(-6)
                                .setDuration(Buff.INFINITY)
                                .create())
                        .addBuff(new Buff.BuffBuilder()
                                .setDurationToStart(2)
                                .setDeltaHP(-4)
                                .setDuration(Buff.INFINITY)
                                .create())
                        .create())
                .setAttackType(new Melee())
                .setAp(2)
                .setHp(8)
                .setManaCost(5)
                .setBuyPrice(400)
                .setSellPrice(400)
                .setName("gorge sefid")
                .create()
        );
        //23
        cards.add(new Minion.MinionBuilder()
                .setSpecialPowerCastTime(ON_ATTACK)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.MINION, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDurationToStart(1)
                                .setDeltaHP(-8)
                                .setDuration(Buff.INFINITY)
                                .create())
                        .create())
                .setAttackType(new Melee())
                .setAp(2)
                .setHp(6)
                .setManaCost(4)
                .setBuyPrice(400)
                .setSellPrice(400)
                .setName("palang")
                .create()
        );
        //24
        cards.add(new Minion.MinionBuilder()
                .setSpecialPowerCastTime(ON_ATTACK)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.MINION, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDurationToStart(1)
                                .setDeltaHP(-6)
                                .setDuration(Buff.INFINITY)
                                .create())
                        .create())
                .setAttackType(new Melee())
                .setAp(1)
                .setHp(6)
                .setManaCost(3)
                .setSellPrice(400)
                .setBuyPrice(400)
                .setName("gorg")
                .create()
        );
        //25
        cards.add(new Minion.MinionBuilder()
                .setSpecialPowerCastTime(PASSIVE)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new UnitsAdjacentToCell(TargetType.MINION, TargetTeam.FRIEND, TargetAttackType.ANY, true))
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaAP(2)
                                .setHalfTurnDuration()
                                .create())
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaHP(-1)
                                .setHalfTurnDuration()
                                .create())
                        .create())
                .setAttackType(new Ranged(3))
                .setAp(4)
                .setHp(5)
                .setManaCost(4)
                .setSellPrice(550)
                .setBuyPrice(550)
                .setName("jadoogar")
                .create()
        );
        //26
        cards.add(new Minion.MinionBuilder()
                .setSpecialPowerCastTime(PASSIVE)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new UnitsAdjacentToCell(TargetType.MINION, TargetTeam.FRIEND, TargetAttackType.ANY, true))
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaAP(2)
                                .setHalfTurnDuration()
                                .create())
                        .addBuff(new Buff.BuffBuilder()
                                .setHoly(1)
                                .setHalfTurnDuration()
                                .create())
                        .create())
                .setAttackType(new Ranged(5))
                .setAp(6)
                .setHp(6)
                .setManaCost(6)
                .setBuyPrice(550)
                .setSellPrice(550)
                .setName("jadoogare azam")
                .create()
        );
        //27
        cards.add(new Minion.MinionBuilder()
                .setSpecialPowerCastTime(PASSIVE)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new AnyUnit(TargetType.MINION, TargetTeam.FRIEND, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaAP(1)
                                .setHalfTurnDuration()
                                .create())
                        .create())
                .setAttackType(new Ranged(4))
                .setAp(4)
                .setHp(10)
                .setManaCost(5)
                .setSellPrice(500)
                .setBuyPrice(500)
                .setName("gen")
                .create()
        );
        //28
        cards.add(new Minion.MinionBuilder()
                .setNotDisarmable()
                .setAttackType(new Melee())
                .setAp(14)
                .setHp(10)
                .setManaCost(6)
                .setBuyPrice(500)
                .setSellPrice(500)
                .setName("goraze vahshi")
                .create()
        );
        //29
        cards.add(new Minion.MinionBuilder()
                .setNotGetPoisoned()
                .setAttackType(new Melee())
                .setAp(12)
                .setHp(20)
                .setManaCost(8)
                .setBuyPrice(400)
                .setSellPrice(400)
                .setName("piran")
                .create()
        );
        //30
        cards.add(new Minion.MinionBuilder()
                .setNotGetNegativeEffect()
                .setAttackType(new Ranged(5))
                .setAp(7)
                .setHp(5)
                .setManaCost(4)
                .setBuyPrice(450)
                .setSellPrice(450)
                .setName("giv")
                .create()
        );
        //31
        cards.add(new Minion.MinionBuilder()
                .setSpecialPowerCastTime(ON_SPAWN)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new OneRandomUnit(TargetType.MINION, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaHP(-16)
                                .setDuration(Buff.INFINITY)
                                .create())
                        .create())
                .setAttackType(new Melee())
                .setAp(9)
                .setHp(16)
                .setManaCost(8)
                .setSellPrice(450)
                .setBuyPrice(450)
                .setName("bahman")
                .create()
        );
        //32
        cards.add(new Minion.MinionBuilder()
                .setNotGetWeakerAttack()
                .setAttackType(new Melee())
                .setAp(8)
                .setHp(14)
                .setManaCost(7)
                .setBuyPrice(400)
                .setSellPrice(400)
                .setName("ashkboos")
                .create()
        );
        //33
        cards.add(new Minion.MinionBuilder()
                .setAttackType(new Ranged(3))
                .setAp(20)
                .setHp(6)
                .setManaCost(4)
                .setSellPrice(500)
                .setBuyPrice(500)
                .setName("iraj")
                .create()
        );
        //34
        cards.add(new Minion.MinionBuilder()
                .setAttackType(new Hybrid(2))
                .setAp(8)
                .setHp(30)
                .setManaCost(9)
                .setSellPrice(600)
                .setBuyPrice(600)
                .setName("ghoole bozorg")
                .create()
        );
        //35
        cards.add(new Minion.MinionBuilder()
                .setSpecialPowerCastTime(ON_ATTACK)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.UNIT, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDispel()
                                .create())
                        .create())
                .setAttackType(new Melee())
                .setAp(4)
                .setHp(10)
                .setManaCost(4)
                .setBuyPrice(550)
                .setSellPrice(550)
                .setName("ghoole do sar")
                .create()
        );
        //36
        cards.add(new Minion.MinionBuilder()
                .setSpecialPowerCastTime(ON_SPAWN)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new UnitsAdjacentToCell(TargetType.MINION, TargetTeam.ENEMY, TargetAttackType.ANY, false))
                        .addBuff(new Buff.BuffBuilder()
                                .setStun()
                                .setDuration(1)
                                .create())
                        .create())
                .setAttackType(new Ranged(5))
                .setAp(4)
                .setHp(3)
                .setManaCost(3)
                .setSellPrice(500)
                .setBuyPrice(500)
                .setName("nane sarma")
                .create()
        );
        //37
        cards.add(new Minion.MinionBuilder()
                .setSpecialPowerCastTime(PASSIVE)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.MINION, TargetTeam.FRIEND, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setHoly(12)
                                .setHalfTurnDuration()
                                .create())
                        .create())
                .setAttackType(new Melee())
                .setAp(1)
                .setHp(1)
                .setManaCost(3)
                .setSellPrice(650)
                .setBuyPrice(650)
                .setName("foolad zereh")
                .create()
        );
        //38
        cards.add(new Minion.MinionBuilder()
                .setSpecialPowerCastTime(ON_DEATH)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new AnyUnit(TargetType.HERO, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDamage(6)
                                .create())
                        .create())
                .setAttackType(new Melee())
                .setAp(5)
                .setHp(8)
                .setManaCost(4)
                .setBuyPrice(350)
                .setSellPrice(350)
                .setName("siavash")
                .create()
        );
        //39
        cards.add(new Minion.MinionBuilder()
                .setCombo()
                .setAttackType(new Melee())
                .setAp(4)
                .setHp(10)
                .setManaCost(5)
                .setSellPrice(600)
                .setBuyPrice(600)
                .setName("shahghool")
                .create()
        );
        //40
        cards.add(new Minion.MinionBuilder()
                .setCombo()
                .setAttackType(new Melee())
                .setAp(6)
                .setHp(6)
                .setManaCost(3)
                .setBuyPrice(600)
                .setBuyPrice(600)
                .setName("arzhang div")
                .create()
        );
    }

    private static void addSpells(ArrayList<Card> cards) {
        //1
        cards.add(new SpellCard.SpellCardBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.UNIT, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDisarm()
                                .setDuration(Buff.INFINITY)
                                .create())
                        .create())
                .setManaCost(0)
                .setBuyPrice(1000)
                .setSellPrice(1000)
                .setName("Total Disarm")
                .create()
        );
        //2
        cards.add(new SpellCard.SpellCardBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new SquareOfCells(2))
                        .addBuff(new Buff.BuffBuilder()
                                .setDispel()
                                .create())
                        .create())
                .setManaCost(2)
                .setSellPrice(1500)
                .setBuyPrice(1500)
                .setName("Area Disepel")
                .create()
        );
        //3
        cards.add(new SpellCard.SpellCardBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.UNIT, TargetTeam.FRIEND, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaAP(2)
                                .setDuration(Buff.INFINITY)
                                .setNotDispelable()
                                .create())
                        .create())
                .setManaCost(1)
                .setBuyPrice(250)
                .setSellPrice(250)
                .setName("Empower")
                .create()
        );
        //4
        cards.add(new SpellCard.SpellCardBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.UNIT, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDamage(4)
                                .create())

                        .create())
                .setManaCost(1)
                .setSellPrice(400)
                .setBuyPrice(400)
                .setName("Fireball")
                .create()
        );
        //5
        cards.add(new SpellCard.SpellCardBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.HERO, TargetTeam.FRIEND, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaAP(4)
                                .setDuration(Buff.INFINITY)
                                .setNotDispelable()
                                .create())
                        .create())
                .setManaCost(2)
                .setBuyPrice(450)
                .setSellPrice(450)
                .setName("God Strength")
                .create()
        );
        //6
        cards.add(new SpellCard.SpellCardBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new SquareOfCells(2))
                        .addBuff(new Buff.BuffBuilder()
                                .setPoison(2)
                                .setDuration(2)
                                .create())
                        .create())
                .setManaCost(3)
                .setSellPrice(600)
                .setBuyPrice(600)
                .setName("HellFire")
                .create()
        );
        //7
        cards.add(new SpellCard.SpellCardBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.HERO, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDamage(8)
                                .create())
                        .create())
                .setManaCost(2)
                .setBuyPrice(1250)
                .setSellPrice(1250)
                .setName("Lightening Bolt")
                .create()
        );
        //8
        cards.add(new SpellCard.SpellCardBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new SquareOfCells(3))
                        .addBuff(new Buff.BuffBuilder()
                                .setPoison(1)
                                .setDuration(1)
                                .create())
                        .create())
                .setManaCost(5)
                .setSellPrice(900)
                .setBuyPrice(900)
                .setName("Poison Lake")
                .create()
        );
        //9
        cards.add(new SpellCard.SpellCardBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.UNIT, TargetTeam.FRIEND, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaAP(4)
                                .setDuration(3)
                                .create())
                        .addBuff(new Buff.BuffBuilder()
                                .setDisarm()
                                .create())
                        .create())
                .setManaCost(0)
                .setSellPrice(650)
                .setBuyPrice(650)
                .setName("Madness")
                .create());
        //10
        cards.add(new SpellCard.SpellCardBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new AnyUnit(TargetType.UNIT, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDisarm()
                                .setDuration(1)
                                .create())
                        .create())
                .setManaCost(9)
                .setBuyPrice(2000)
                .setSellPrice(2000)
                .setName("All Disarm")
                .create()
        );
        //11
        cards.add(new SpellCard.SpellCardBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new AnyUnit(TargetType.UNIT, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDuration(4)
                                .setPoison(1)
                                .create())
                        .create())
                .setManaCost(8)
                .setSellPrice(1500)
                .setBuyPrice(1500)
                .setName("All Poison")
                .create());
        //12
        cards.add(new SpellCard.SpellCardBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.UNIT, TargetTeam.ANY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDispel()
                                .create())
                        .create())
                .setManaCost(0)
                .setSellPrice(2100)
                .setBuyPrice(2100)
                .setName("Dispel")
                .create()
        );
        //13
        cards.add(new SpellCard.SpellCardBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.UNIT, TargetTeam.FRIEND, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaHP(-6)
                                .setDuration(Buff.INFINITY)
                                .create())
                        .addBuff(new Buff.BuffBuilder()
                                .setDuration(3)
                                .setHoly(2)
                                .create())
                        .create())
                .setManaCost(0)
                .setSellPrice(2250)
                .setBuyPrice(2250)
                .setName("Health with profit")
                .create()
        );
        //14
        cards.add(new SpellCard.SpellCardBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.UNIT, TargetTeam.FRIEND, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaAP(6)
                                .setDuration(Buff.INFINITY)
                                .create())
                        .create())
                .setManaCost(2)
                .setBuyPrice(2500)
                .setSellPrice(2500)
                .setName("Power Up")
                .create()
        );
        //15
        cards.add(new SpellCard.SpellCardBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new AnyUnit(TargetType.UNIT, TargetTeam.FRIEND, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaAP(2)
                                .setDuration(Buff.INFINITY)
                                .create())
                        .create())
                .setManaCost(4)
                .setBuyPrice(2000)
                .setSellPrice(2000)
                .setName("All Power")
                .create());
        //16
        cards.add(new SpellCard.SpellCardBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new EnemiesInColumn())
                        .addBuff(new Buff.BuffBuilder()
                                .setDamage(6)
                                .create())
                        .create())
                .setManaCost(4)
                .setSellPrice(1500)
                .setBuyPrice(1500)
                .setName("All Attack")
                .create());
        //17
        cards.add(new SpellCard.SpellCardBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.MINION, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaAP(-4)
                                .setDuration(Buff.INFINITY)
                                .create())
                        .create())
                .setManaCost(1)
                .setBuyPrice(1000)
                .setBuyPrice(1000)
                .setName("Weakening")
                .create()
        );
        //18
        cards.add(new SpellCard.SpellCardBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.MINION, TargetTeam.FRIEND, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaAP(8)
                                .setDuration(Buff.INFINITY)
                                .create())
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaHP(-6)
                                .setDuration(Buff.INFINITY)
                                .create())
                        .create())
                .setManaCost(2)
                .setBuyPrice(1600)
                .setSellPrice(1600)
                .setName("Sacrifice")
                .create());
        //19
        cards.add(new SpellCard.SpellCardBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new RandomEnemyMinionAdjacentToHero())
                        .addBuff(new Buff.BuffBuilder() // it kills enemy :))
                                .setDeltaHP(Buff.INFINITY)
                                .setDuration(Buff.INFINITY)
                                .setNotDispelable()
                                .create())
                        .create())
                .setManaCost(9)
                .setSellPrice(1750)
                .setBuyPrice(1750)
                .setName("Kings Guard")
                .create());
        //20
        cards.add(new SpellCard.SpellCardBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.UNIT, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setStun()
                                .setDuration(2)
                                .create())
                        .create())
                .setManaCost(1)
                .setSellPrice(1200)
                .setBuyPrice(1200)
                .setName("Shock")
                .create());
    }

    private static void addHeroes(ArrayList<Card> cards) {
        //1
        cards.add(new Hero.HeroBuilder()
                .setSpellCoolDown(2)
                .setSpellManaCost(1)
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new AnyUnit(TargetType.HERO, TargetTeam.FRIEND, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaAP(4)
                                .setDuration(Buff.INFINITY)
                                .create())
                        .create())
                .setAttackType(new Melee())
                .setAp(4)
                .setHp(50)
                .setManaCost(0)
                .setSellPrice(8000)
                .setBuyPrice(8000)
                .setName("dive sefid")
                .create());
        //2
        cards.add(new Hero.HeroBuilder()
                .setSpellCoolDown(8)
                .setSpellManaCost(5)
                .setSpell(new Spell.SpellBuilder()
                        .addBuff(new Buff.BuffBuilder()
                                .setStun()
                                .setDuration(1)
                                .create())
                        .setTargetSociety(new AnyUnit(TargetType.UNIT, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .create())
                .setAttackType(new Melee())
                .setAp(4)
                .setHp(50)
                .setManaCost(0)
                .setBuyPrice(9000)
                .setSellPrice(9000)
                .setName("simorgh")
                .create()
        );
        //3
        cards.add(new Hero.HeroBuilder()
                .setSpellCoolDown(1)
                .setSpellManaCost(0)
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.UNIT, TargetTeam.ANY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDisarm()
                                .setDuration(Buff.INFINITY)
                                .create())
                        .create())
                .setAttackType(new Melee())
                .setAp(4)
                .setHp(50)
                .setManaCost(0)
                .setSellPrice(8000)
                .setBuyPrice(8000)
                .setName("ezhdehaye haft sar")
                .create());
        //4
        cards.add(new Hero.HeroBuilder()
                .setSpellCoolDown(2)
                .setSpellManaCost(1)
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.UNIT, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDisarm()
                                .setDuration(1)
                                .create())
                        .create())
                .setAttackType(new Melee())
                .setAp(4)
                .setHp(50)
                .setManaCost(0)
                .setBuyPrice(8000)
                .setSellPrice(8000)
                .setName("rakhsh")
                .create());
        //5
        cards.add(new Hero.HeroBuilder()
                .setSpecialPowerCastTime(ON_ATTACK)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.UNIT, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setPoison(1)
                                .setDuration(3)
                                .create())
                        .create())
                .setAttackType(new Melee())
                .setAp(2)
                .setHp(50)
                .setManaCost(0)
                .setSellPrice(10000)
                .setBuyPrice(10000)
                .setName("zahhak")
                .create());
        //6
        cards.add(new Hero.HeroBuilder()
                .setSpellCoolDown(3)
                .setSpellManaCost(1)
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new SquareOfCells(1))
                        .addBuff(new Buff.BuffBuilder()
                                .setHoly(1)
                                .setDuration(3)
                                .create())
                        .create())
                .setAttackType(new Melee())
                .setAp(4)
                .setHp(50)
                .setManaCost(0)
                .setBuyPrice(8000)
                .setSellPrice(8000)
                .setName("kave")
                .create());
        //7
        cards.add(new Hero.HeroBuilder()
                .setSpellCoolDown(2)
                .setSpellManaCost(2)
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new UnitsInHeroRow())
                        .addBuff(new Buff.BuffBuilder()
                                .setDamage(4)
                                .create())
                        .create())
                .setAttackType(new Ranged(6))
                .setAp(2)
                .setHp(30)
                .setManaCost(0)
                .setSellPrice(10000)
                .setBuyPrice(10000)
                .setName("arash")
                .create());
        //8
        cards.add(new Hero.HeroBuilder()
                .setSpellCoolDown(2)
                .setSpellManaCost(1)
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.UNIT, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDispel()
                                .create())
                        .create())
                .setAttackType(new Ranged(3))
                .setAp(3)
                .setHp(40)
                .setManaCost(0)
                .setBuyPrice(11000)
                .setSellPrice(11000)
                .setName("afsane")
                .create());
        //9
        cards.add(new Hero.HeroBuilder()
                .setSpecialPowerCastTime(PASSIVE)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.HERO, TargetTeam.FRIEND, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setHoly(3)
                                .setHalfTurnDuration()
                                .create())
                        .create())
                .setAttackType(new Hybrid(3))
                .setAp(3)
                .setHp(35)
                .setManaCost(0)
                .setSellPrice(12000)
                .setBuyPrice(12000)
                .setName("esfandiar")
                .create());
        //10
        cards.add(new Hero.HeroBuilder()
                .setAttackType(new Hybrid(4))
                .setAp(7)
                .setHp(55)
                .setManaCost(0)
                .setBuyPrice(8000)
                .setSellPrice(8000)
                .setName("rostam")
                .create());
    }

    public static void initShopUsableItems(ArrayList<Item> items) {
        //1
        items.add(new ManaItem.ManaItemBuilder()
                .setMana(1)
                .setDuration(3)
                .setType(Item.Type.USABLE)
                .setBuyPrice(300)
                .setSellPrice(300)
                .setName("taje Danaii")
                .create());
        //2
        items.add(new SpellItem.SpellItemBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new AnyUnit(TargetType.HERO, TargetTeam.FRIEND, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setHoly(12)
                                .setDuration(Buff.INFINITY)
                                .create())
                        .create())
                .setType(Item.Type.USABLE)
                .setBuyPrice(4000)
                .setSellPrice(4000)
                .setName("namoose Separ")
                .create());
        //3
        items.add(new SpecialPowerAdderItem.SpecialPowerAdderItemBuilder()
                .addTargetAttackType(SpecialPowerAdderItem.TargetAttackType.RANGED)
                .addTargetAttackType(SpecialPowerAdderItem.TargetAttackType.HYBRID)
                .setTargetSelection(SpecialPowerAdderItem.TargetSelection.ALL)
                .setTargetType(SpecialPowerAdderItem.TargetType.HERO)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.UNIT, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDisarm()
                                .setDuration(1)
                                .create())
                        .create())
                .setSpecialPowerCastTime(ON_ATTACK)//todo check at the end
                .setType(Item.Type.USABLE)
                .setBuyPrice(30000)
                .setSellPrice(30000)
                .setName("kamane Damol")
                .create());
        //6
        items.add(new SpellItem.SpellItemBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new AnyUnit(TargetType.HERO, TargetTeam.ENEMY, TargetAttackType.RANGED_HYBRID))
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaAP(-2)
                                .setDuration(Buff.INFINITY)
                                .setNotDispelable()
                                .create())
                        .create())
                .setType(Item.Type.USABLE)
                .setName("pare simorgh")
                .setBuyPrice(3500)
                .setSellPrice(3500)
                .create());
        //12
        items.add(new SpecialPowerAdderItem.SpecialPowerAdderItemBuilder()
                .setTargetAttackTypeAll()
                .setTargetSelection(SpecialPowerAdderItem.TargetSelection.ALL)
                .setTargetType(SpecialPowerAdderItem.TargetType.UNIT)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new OneRandomUnit(TargetType.UNIT, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaAP(-2)
                                .setDuration(1)
                                .create())
                        .create())
                .setSpecialPowerCastTime(ON_ATTACK)
                .setType(Item.Type.USABLE)
                .setName("Terror Hood")
                .setSellPrice(5000)
                .setBuyPrice(5000)
                .create());
        //14
        items.add(new ManaItem.ManaItemBuilder()
                .setMana(1)
                .setDuration(Buff.INFINITY)
                .setType(Item.Type.USABLE)
                .setName("King Wisdom")
                .setBuyPrice(9000)
                .setSellPrice(9000)
                .create());
        //15
        items.add(new SpecialPowerAdderItem.SpecialPowerAdderItemBuilder()
                .setTargetAttackTypeAll()
                .setTargetSelection(SpecialPowerAdderItem.TargetSelection.ALL)
                .setTargetType(SpecialPowerAdderItem.TargetType.UNIT)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new AnyUnit(TargetType.HERO, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDamage(1)
                                .create())
                        .create())
                .setSpecialPowerCastTime(ON_SPAWN)
                .setType(Item.Type.USABLE)
                .setSellPrice(15000)
                .setBuyPrice(15000)
                .setName("Assasination Dagger")
                .create());
        //16
        items.add(new SpecialPowerAdderItem.SpecialPowerAdderItemBuilder()
                .setTargetAttackTypeAll()
                .setTargetSelection(SpecialPowerAdderItem.TargetSelection.ALL)
                .setTargetType(SpecialPowerAdderItem.TargetType.UNIT)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new OneRandomUnit(TargetType.UNIT, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setPoison(1)
                                .setDuration(1)
                                .create())
                        .create())
                .setSpecialPowerCastTime(ON_ATTACK)
                .setType(Item.Type.USABLE)
                .setBuyPrice(7000)
                .setSellPrice(7000)
                .setName("Poisonous Dagger")
                .create());
        //17
        items.add(new SpecialPowerAdderItem.SpecialPowerAdderItemBuilder()
                .setTargetAttackTypeAll()
                .setTargetSelection(SpecialPowerAdderItem.TargetSelection.ALL)
                .setTargetType(SpecialPowerAdderItem.TargetType.HERO)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.UNIT, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDuration(1)
                                .setDisarm()
                                .create())
                        .create())
                .setSpecialPowerCastTime(ON_ATTACK)
                .setType(Item.Type.USABLE)
                .setName("Shock Hammer")
                .setSellPrice(15000)
                .setBuyPrice(15000)
                .create());
        //18
        items.add(new SpecialPowerAdderItem.SpecialPowerAdderItemBuilder()
                .setTargetAttackTypeAll()
                .setTargetSelection(SpecialPowerAdderItem.TargetSelection.ALL)
                .setTargetType(SpecialPowerAdderItem.TargetType.UNIT)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new OneRandomUnit(TargetType.UNIT, TargetTeam.FRIEND, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaAP(1)
                                .setDuration(Buff.INFINITY)
                                .create())
                        .create())
                .setSpecialPowerCastTime(ON_DEATH)
                .setType(Item.Type.USABLE)
                .setSellPrice(25000)
                .setBuyPrice(25000)
                .setName("Soul Eater")
                .create());
        //19
        items.add(new SpecialPowerAdderItem.SpecialPowerAdderItemBuilder()
                .setTargetAttackTypeAll()
                .setTargetSelection(SpecialPowerAdderItem.TargetSelection.ALL)
                .setTargetType(SpecialPowerAdderItem.TargetType.MINION)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.MINION, TargetTeam.FRIEND, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setHoly(1)
                                .setDuration(2)
                                .create())
                        .create())
                .setSpecialPowerCastTime(ON_SPAWN)
                .setType(Item.Type.USABLE)
                .setName("ghosle tamid")
                .setBuyPrice(20000)
                .setSellPrice(20000)
                .create());


    }

    public static ArrayList<Item> initCollectibleItems() {
        ArrayList<Item> items = new ArrayList<>();


        //4
        items.add(new SpellItem.SpellItemBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new OneRandomUnit(TargetType.UNIT, TargetTeam.FRIEND, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaHP(6)
                                .setDuration(Buff.INFINITY)
                                .setNotDispelable()
                                .create())
                        .create())
                .setType(Item.Type.COLLECTIBLE)
                .setName("nooshdaroo")
                .create());
        //5
        items.add(new SpellItem.SpellItemBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new OneRandomUnit(TargetType.UNIT, TargetTeam.FRIEND,
                                TargetAttackType.RANGED_HYBRID))
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaAP(2)
                                .setDuration(Buff.INFINITY)
                                .setNotDispelable()
                                .create())
                        .create())
                .setType(Item.Type.COLLECTIBLE)
                .setName("tire do shakh")
                .create()
        );
        //7
        items.add(new SpellItem.SpellItemBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new OneRandomUnit(TargetType.MINION, TargetTeam.FRIEND, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaAP(3)
                                .setDuration(Buff.INFINITY)
                                .create())
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaHP(3)
                                .setDuration(Buff.INFINITY)
                                .setNotDispelable()
                                .create())
                        .create())
                .setType(Item.Type.COLLECTIBLE)
                .setName("exir")
                .create());
        //8
        items.add(new ManaItem.ManaItemBuilder()
                .setDuration(1)
                .setMana(3)
                .setType(Item.Type.COLLECTIBLE)
                .setName("majoone mana")
                .create());
        //9
        items.add(new SpellItem.SpellItemBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new OneRandomUnit(TargetType.UNIT, TargetTeam.FRIEND, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setHoly(10)
                                .setDuration(2)
                                .create())
                        .create())
                .setType(Item.Type.COLLECTIBLE)
                .setName("majoone rooin tani")
                .create());
        //10
        items.add(new SpecialPowerAdderItem.SpecialPowerAdderItemBuilder()
                .setTargetAttackTypeAll()
                .setTargetSelection(SpecialPowerAdderItem.TargetSelection.RANDOM)
                .setTargetType(SpecialPowerAdderItem.TargetType.MINION)
                .setSpecialPower(new Spell.SpellBuilder()
                        .setTargetSociety(new OneRandomNearestUnit(TargetType.UNIT, TargetTeam.ENEMY, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDamage(8)
                                .create())
                        .create())
                .setSpecialPowerCastTime(ON_DEATH)
                .setType(Item.Type.COLLECTIBLE)
                .setName("nefrine marg")
                .create());
        //11
        items.add(new SpellItem.SpellItemBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new OneRandomUnit(TargetType.UNIT, TargetTeam.FRIEND, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaAP(2)
                                .setDuration(Buff.INFINITY)
                                .setNotDispelable()
                                .create())
                        .create())
                .setType(Item.Type.COLLECTIBLE)
                .setName("Random damage")
                .create());
        //13
        items.add(new SpellItem.SpellItemBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new OneRandomUnit(TargetType.UNIT, TargetTeam.FRIEND, TargetAttackType.ANY))
                        .addBuff(new Buff.BuffBuilder()
                                .setDeltaAP(6)
                                .setDuration(Buff.INFINITY)
                                .setNotDispelable()
                                .create())
                        .create())
                .setType(Item.Type.COLLECTIBLE)
                .setName("Blades of agility")
                .create());
        //20
        items.add(new SpellItem.SpellItemBuilder()
                .setSpell(new Spell.SpellBuilder()
                        .setTargetSociety(new OneUnit(TargetType.UNIT, TargetTeam.FRIEND, TargetAttackType.MELEE))
                        .addBuff(new Buff.BuffBuilder()
                                .setDuration(Buff.INFINITY)
                                .setDeltaAP(5)
                                .setNotDispelable()
                                .create())
                        .create())
                .setType(Item.Type.COLLECTIBLE)
                .setName("shamshire chini")
                .create());


        return items;
    }

    public static Item getRandomCollectible() {
        int size = collectibles.size();
        int randomNumber = Math.abs(new Random().nextInt()) % size;
        return collectibles.get(randomNumber).getCopy(false);
    }
}
